services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:Raj%402025@egon-postgres.render.com:5432/ticketing_system_h2jh?sslmode=require

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api